// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AgentGoalEventDto = { goal_id: string, revision: number, event_type: string, status: string | null, reason: string | null, model_id: string | null, spent_micros: number | null, limit_micros: number | null, receipt_digest: string | null, size_bytes: number | null, };
