// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ReviewUsageDto } from "./ReviewUsageDto";

export type AgentEventDto = { run_id: string, sequence: number, attempt_id: number, event_type: string, provider_id: string | null, model_id: string | null, response_id: string | null, delta: string | null, call_id: string | null, tool_name: string | null, usage: ReviewUsageDto | null, error_code: string | null, will_retry: boolean | null, };
