// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AgentGoalSnapshotDto } from "./AgentGoalSnapshotDto";
import type { AgentSessionMessageDto } from "./AgentSessionMessageDto";

export type AgentSessionSnapshotDto = { session_id: string, revision: number, memory_summary: string | null, recent_messages: Array<AgentSessionMessageDto>, active_goal: AgentGoalSnapshotDto | null, };
