// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AgentGoalUsageDto } from "./AgentGoalUsageDto";

export type AgentGoalSnapshotDto = { goal_id: string, session_id: string, revision: number, objective: string, model_id: string, status: string, pause_reason: string | null, block_reason: string | null, usage_by_model: Array<AgentGoalUsageDto>, slice_index: number, steering_count: number, completion_candidate_pending: boolean, final_text: string | null, };
