// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AgentGoalUsageDto = { model_id: string, currency: string | null, input_tokens: number, cached_input_tokens: number, output_tokens: number, tool_calls: number, spent_micros: number, limit_micros: number | null, limit_tokens: number | null, };
