// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ReviewUsageDto } from "./ReviewUsageDto";

export type AgentSessionTurnResultDto = { session_id: string, run_id: string, revision: number, final_text: string, usage: ReviewUsageDto, model_rounds: number, retrieval_count: number, };
