// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 当前分支相对上游的领先/落后 DTO。
 */
export type AheadBehindDto = { ahead: number, behind: number, };
