// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * blame 一行 DTO。
 */
export type BlameLineDto = { line_no: number, commit_id: string, short_id: string, author_name: string, timestamp: number, content: string, };
