// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 删分支影响预览 DTO:`unmerged_commits`>0 时前端做强危险二次确认。
 */
export type BranchDeleteImpactDto = { unmerged_commits: number, sample_summaries: Array<string>, };
