// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ChangeWarningSeverityDto } from "./ChangeWarningSeverityDto";

export type ChangeWarningDto = { code: string, severity: ChangeWarningSeverityDto, message: string, paths: Array<string>, };
