// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ChangePlanFileDto = { path: string, state: string, staged: boolean, additions: number, deletions: number, };
