// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ChangePlanInputDto = { run_id: string, repo_path: string, model_id: string | null, };
