// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ChangePlanFileDto } from "./ChangePlanFileDto";

export type ChangeCommitGroupDto = { id: string, title: string, rationale: string, commit_message: string, files: Array<ChangePlanFileDto>, executable: boolean, blocked_reason: string | null, };
