// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ChangeCommitGroupDto } from "./ChangeCommitGroupDto";
import type { ChangeWarningDto } from "./ChangeWarningDto";
import type { ReviewUsageDto } from "./ReviewUsageDto";

export type ChangePlanResultDto = { snapshot_id: string, summary: string, warnings: Array<ChangeWarningDto>, groups: Array<ChangeCommitGroupDto>, enhanced: boolean, usage: ReviewUsageDto, model_id: string, provider_attempts: number, };
