// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 传给前端的提交 DTO。这里特意和领域模型 Commit 分开:
 * 领域模型可以很丰富,DTO 只暴露前端真正需要的字段。
 */
export type CommitDto = { id: string, short_id: string, summary: string, 
/**
 * 提交信息正文(首行 summary 之后的部分);无正文时为空串。
 */
body: string, author_name: string, author_email: string, timestamp: number, parents: Array<string>, };
