// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CommitChangeGroupInputDto = { run_id: string, repo_path: string, snapshot_id: string, group_id: string, commit_message: string, confirmed: boolean, };
