// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CreateAgentGoalInputDto = { repo_path: string, goal_id: string, model_id: string, message: string, };
