// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SegDto } from "./SegDto";

/**
 * 行级 diff 的一行 DTO。kind:context | add | del。
 */
export type DiffLineDto = { kind: string, old_lineno: number | null, new_lineno: number | null, content: string, 
/**
 * 行内词级段;None = 整行着色。
 */
emphasis?: Array<SegDto>, };
