// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ExtendAgentBudgetInputDto = { repo_path: string, goal_id: string, expected_revision: number, model_id: string, currency: string | null, new_limit_micros: number | null, new_limit_tokens: number | null, };
