// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 一次 fetch 的结果 DTO。
 */
export type FetchResultDto = { remote: string, summary: string, };
