// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 工作区单个文件状态的 DTO。state 用字符串,前端直接渲染徽章。
 */
export type FileEntryDto = { path: string, state: string, staged: boolean, };
