// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { HunkDto } from "./HunkDto";
import type { ImageRefDto } from "./ImageRefDto";

export type FileDiffDto = { path: string, is_binary: boolean, too_large: boolean, is_lfs_pointer: boolean, lfs_size: string, is_image: boolean, old_image: ImageRefDto | null, new_image: ImageRefDto | null, hunks: Array<HunkDto>, };
