// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CommitDto } from "./CommitDto";
import type { GraphSegDto } from "./GraphSegDto";
import type { RefDto } from "./RefDto";

/**
 * 图谱一行:嵌入提交信息 + 节点列/颜色 + 上下半段连线 + 指向该提交的引用。
 */
export type GraphRowDto = { commit: CommitDto, column: number, color: number, top: Array<GraphSegDto>, bottom: Array<GraphSegDto>, 
/**
 * 指向本行提交的引用(分支/远程/HEAD);多数行为空。
 */
refs: Array<RefDto>, 
/**
 * 同步标记:"" 普通 | "outgoing" 已 commit 未 push | "incoming" 已 fetch 未 pull。
 */
sync: string, };
