// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 图谱中一段连线:在某行单元格内,从 `from` 列连到 `to` 列。
 * 上半段语义为 顶边→节点(中点),下半段为 节点(中点)→底边。
 */
export type GraphSegDto = { from: number, to: number, color: number, };
