// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type HistoryInvestigationFindingDto = { title: string, explanation: string, commit_ids: Array<string>, paths: Array<string>, };
