// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type HistoryInvestigationInputDto = { run_id: string, repo_path: string, question: string, file: string | null, model_id: string, };
