// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 一侧图片的取图句柄(M6.2:不再内联 base64)。前端用 `(mime, oid)` + 文件路径经
 * `read_image` 命令取原始字节转 Blob URL。`oid` 空串表示读工作区文件。
 */
export type ImageRefDto = { mime: string, oid: string, };
