// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type IssueTriageProposalDto = { summary: string, category: string, priority: string, confidence: number, suggested_labels: Array<string>, suspected_duplicate_numbers: Array<number>, suggested_reply: string, rationale: Array<string>, };
