// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type IssueTriagePublishActionResultDto = { action_id: string, kind: string, label: string | null, status: string, error_code: string | null, };
