// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { IssueSnapshotDto } from "./IssueSnapshotDto";
import type { IssueTriagePublishActionResultDto } from "./IssueTriagePublishActionResultDto";

export type IssueTriagePublishResultDto = { publish_id: string, snapshot: IssueSnapshotDto | null, actions: Array<IssueTriagePublishActionResultDto>, };
