// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { IssueCommentDto } from "./IssueCommentDto";
import type { IssueLabelDto } from "./IssueLabelDto";
import type { IssueSnapshotDto } from "./IssueSnapshotDto";
import type { IssueSummaryDto } from "./IssueSummaryDto";

export type IssueContextDto = { issue: IssueSummaryDto, body: string, comments: Array<IssueCommentDto>, comments_truncated: boolean, available_labels: Array<IssueLabelDto>, similar_issues: Array<IssueSummaryDto>, snapshot: IssueSnapshotDto, };
