// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { IssueTargetDto } from "./IssueTargetDto";
import type { ReviewLanguageDto } from "./ReviewLanguageDto";

export type IssueTriageInputDto = { run_id: string, target: IssueTargetDto, expected_updated_at: string, expected_comments: number, model_id: string, output_language: ReviewLanguageDto, };
