// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { IssueLabelDto } from "./IssueLabelDto";

export type IssueSummaryDto = { number: number, title: string, url: string, author: string | null, updated_at: string, comments: number, labels: Array<IssueLabelDto>, };
