// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { IssueSnapshotDto } from "./IssueSnapshotDto";
import type { IssueTargetDto } from "./IssueTargetDto";

export type IssueTriagePublishInputDto = { publish_id: string, confirmed: boolean, target: IssueTargetDto, expected_snapshot: IssueSnapshotDto, labels: Array<string>, reply: string | null, };
