// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CommitDto } from "./CommitDto";
import type { FileDiffDto } from "./FileDiffDto";

/**
 * 行历史的一条:某提交 + 它对选中行范围的 diff。
 */
export type LineHistoryEntryDto = { commit: CommitDto, diff: FileDiffDto, };
