// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 一次「合并某分支进当前分支」的成功结果 DTO。
 */
export type MergeResultDto = { summary: string, 
/**
 * 本次是否为快进合并(未产生合并提交)。
 */
fast_forward: boolean, };
