// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { OpLogEntryDto } from "./OpLogEntryDto";

/**
 * 操作日志面板数据:本会话写操作时间线(oldest→newest)+ 当前光标位置。
 * 点击第 i 项 = goto(i),沿时间线 reset --soft 跳过去。
 */
export type OpLogDto = { entries: Array<OpLogEntryDto>, 
/**
 * 当前 HEAD 所在的项下标(高亮「现在在哪」)。
 */
current: number, };
