// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 操作日志的一项:本工具做过的一次写操作的落点。
 */
export type OpLogEntryDto = { 
/**
 * 操作中文名,如 "提交"、"cherry-pick";时间线基点为 "起点"。
 */
label: string, 
/**
 * 该操作后 HEAD 的短 SHA。
 */
target_short: string, 
/**
 * Unix 时间戳(秒),供「几分钟前」显示。
 */
timestamp: number, };
