// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 一次 push 的成功结果 DTO。
 */
export type PushResultDto = { summary: string, 
/**
 * 本次是否顺带建立了上游(首次 push 自动 -u 时为 true,前端可特别提示)。
 */
set_upstream: boolean, };
