// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 指向某 commit 的引用 DTO。kind:head | local | remote。
 */
export type RefDto = { name: string, kind: string, };
