// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 一条 reflog 记录 DTO。`new_oid` 是"重置回这一步"时 reset 的目标提交。
 */
export type ReflogEntryDto = { index: number, selector: string, new_oid: string, new_short: string, message: string, committer_name: string, timestamp: number, };
