// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 一个远程的展示信息 DTO(名字 + fetch URL)。供「管理远程」面板。
 */
export type RemoteInfoDto = { name: string, url: string, };
