// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ResumeAgentGoalInputDto = { repo_path: string, goal_id: string, expected_revision: number, model_id: string | null, };
