// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ReviewProgressEventDto = { run_id: string, stage: string, tool_name: string | null, tool_calls: number | null, };
