// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ReviewModelCapabilitiesDto = { supports_tool_calling: boolean, supports_structured_output: boolean, context_window_tokens: number, max_output_tokens: number, reports_usage: boolean, };
