// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ReviewFindingDto = { id: string, severity: string, path: string, side: string, line: number, title: string, failure_scenario: string, explanation: string, draft_comment: string, };
