// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ReviewFindingDto } from "./ReviewFindingDto";
import type { ReviewUsageDto } from "./ReviewUsageDto";

export type ReviewRunResultDto = { run_id: string, head_sha: string, summary: string, reviewed_files: Array<string>, findings: Array<ReviewFindingDto>, usage: ReviewUsageDto, model_id: string, duration_ms: number, diagnostic_id: string, provider_attempts: number, };
