// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ReviewUsageDto = { input_tokens: number, output_tokens: number, tool_calls: number, };
