// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ReviewModelCapabilitiesDto } from "./ReviewModelCapabilitiesDto";
import type { ReviewModelPricingDto } from "./ReviewModelPricingDto";

export type ReviewModelOptionDto = { id: string, label: string, provider: string, provider_id: string, capabilities: ReviewModelCapabilitiesDto, pricing: ReviewModelPricingDto | null, };
