// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ReviewLanguageDto } from "./ReviewLanguageDto";
import type { ReviewTargetDto } from "./ReviewTargetDto";

export type ReviewRunInputDto = { run_id: string, target: ReviewTargetDto, expected_head_sha: string, selected_files: Array<string>, model_id: string, output_language: ReviewLanguageDto, };
