// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ReviewFileDto } from "./ReviewFileDto";

export type ReviewPreflightDto = { head_sha: string, files: Array<ReviewFileDto>, total_patch_bytes: number, requires_selection: boolean, };
