// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ReviewModelPricingDto = { currency: string, input_cache_hit_per_million_micros: number, input_cache_miss_per_million_micros: number, output_per_million_micros: number, source_url: string, source_version: string, checked_at: string, };
