// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 提交签名 DTO。status: "none" | "good" | "unverified" | "bad"。
 */
export type SignatureInfoDto = { status: string, signer: string, };
