// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SteerAgentGoalInputDto = { repo_path: string, goal_id: string, expected_revision: number, message: string, };
