// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 子模块 DTO。status: "uninitialized" | "up-to-date" | "modified" | "conflict"。
 */
export type SubmoduleInfoDto = { path: string, url: string, head_sha: string, short_sha: string, status: string, describe: string, };
