// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ReviewFindingDto } from "./ReviewFindingDto";
import type { ReviewTargetDto } from "./ReviewTargetDto";

export type SubmitReviewDto = { target: ReviewTargetDto, head_sha: string, findings: Array<ReviewFindingDto>, };
