// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ToolApprovalDecisionDto } from "./ToolApprovalDecisionDto";

export type ToolApprovalResolutionDto = { run_id: string, approval_id: string, decision: ToolApprovalDecisionDto, };
