// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { UndoStepDto } from "./UndoStepDto";

/**
 * 撤销/重做的当前可用性。驱动顶栏「撤销」「重做」两个按钮的显隐与文案。
 * `None` = 该方向无可用项(按钮不显);来自 `RepoContext` 内的操作时间线 + 光标。
 */
export type UndoStateDto = { 
/**
 * 后退一步(撤销最近一次操作)。
 */
can_undo: UndoStepDto | null, 
/**
 * 前进一步(重做刚撤销的操作)。
 */
can_redo: UndoStepDto | null, };
