// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 工作树 DTO。
 */
export type WorktreeInfoDto = { path: string, head_sha: string, short_sha: string, branch: string, is_main: boolean, is_current: boolean, detached: boolean, locked: boolean, bare: boolean, };
